# Generated by Django 5.1.6 on 2025-02-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='option_a_image',
            field=models.ImageField(blank=True, null=True, upload_to='mcq_images/'),
        ),
        migrations.AddField(
            model_name='mcq',
            name='option_b_image',
            field=models.ImageField(blank=True, null=True, upload_to='mcq_images/'),
        ),
        migrations.AddField(
            model_name='mcq',
            name='option_c_image',
            field=models.ImageField(blank=True, null=True, upload_to='mcq_images/'),
        ),
        migrations.AddField(
            model_name='mcq',
            name='option_d_image',
            field=models.ImageField(blank=True, null=True, upload_to='mcq_images/'),
        ),
        migrations.AddField(
            model_name='mcq',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='mcq_images/'),
        ),
    ]
